[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "uv_base"
version = "0.1.0"
authors = [
    { name = "Akinus21", email = "akinus.21.dev@gmail.com" }
]
description = "A Hello World CLI using uv"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "toml",
    "packaging",
    "win10toast; sys_platform == 'win32'",
]
packages = ["uv_base"]  # <- Explicitly specify your package

[tool.setuptools.packages.find]
where = ["uv_base"] 

[project.scripts]
uv_base = "uv_base.__main__:main"
uv_base_update = "uv_base.utils.update:main"
