[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "supreme-research-mcp"
version = "0.1.0"
authors = [
    { name = "Akinus21", email = "akinus.21.dev@gmail.com" }
]
description = "A Hello World CLI using uv"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "toml",
    "packaging",
    "win10toast; sys_platform == 'win32'",
]
packages = ["supreme-research-mcp"]  # <- Explicitly specify your package

[tool.setuptools.packages.find]
where = ["supreme-research-mcp"] 

[project.scripts]
supreme-research-mcp = "supreme-research-mcp.__main__:main"
supreme-research-mcp_update = "supreme-research-mcp.utils.update:main"
