# Config constants (set elsewhere in your settings)
MAX_CONCURRENT_BRAVE = 3
MAX_CONCURRENT_DDG = 3
MAX_CONCURRENT_OPENALEX = 3
MAX_CONCURRENT_ARXIV = 3
MAX_CONCURRENT_CORE = 3
MAX_CONCURRENT_CROSSREF = 3

BRAVE_MAX_RETRIES = 2
BRAVE_RETRY_DELAY = 2

OPENALEX_MAX_RETRIES = 3
OPENALEX_RETRY_DELAY = 3

SEARCH_TIMEOUT = 30